### ISSUE TITLE
where can I find the model? thanks

### ISSUE THREAD

**Issue by nanyyyyyy** [thu-coai/UDIT#1]

**Comment by t1101675** [comment]
We add the download link of the model and evaluation data in README.md

**Comment by nanyyyyyy** [comment]
> We add the download link of the model and evaluation data in README.md

thanks!

**Comment by nanyyyyyy** [comment]
> We add the download link of the model and evaluation data in README.md

Is it the best performance model in your paper? UDIT 700M with 304 Instruction?
